title: Vaishnav Sreekanth Menon
author: Vaishnav Sreekanth Menon

destination: docs

url: "https://vaishnavsm.com"

footer_only_homepage: true
footer_url: "https://github.com/vaishnavsm/vaishnavsm.github.io"
footer_text: "Powered by Jekyll. Theme forked from parchment."

favicon_location: assets/favicon.ico

highlighted_sections:
  - title: Website
    href: https://vaishnavsm.com
  - title: Schedule A Call
    href: https://calendly.com/vaishnavsm/catch-up

# titles come from https://feathericons.com/
socials:
  - href: https://vaishnavsm.com
    title: web
  - href: mailto://hey@vaishnavsm.com
    title: mail
  - href: https://github.com/vaishnavsm
    title: github
  - href: https://www.linkedin.com/in/vaishnavsm/
    title: linkedin
  - href: https://www.instagram.com/_vaishnavsm_/
    title: instagram
  - href: https://vaishnavsm.com/feed.xml
    title: rss

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

exclude:
  - .gitignore
  - .ruby-version
  - lefthook.yml
  - LICENSE
  - README.md
  - Makefile
